### ISSUE TITLE
PyPI classifiers not working, upload universal wheel

### ISSUE THREAD

**Issue by nicktimko** [atdt/monotonic#16]
I noticed that for some reason this package shows up as "Not Python 3 ready" on http://py3readiness.org/ Looking at this on PyPI, there are no classifiers listed on the entry.

Also, if you're mucking around with PyPI, could you upload a [universal wheel](https://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#universal-wheels) (rather than just for Py2?).

**Comment by atdt** [comment]
The trove classifiers were supplied as a tuple rather than a list. PyPI didn't like that, for some reason. Changed it to a list and it now works.

Also uploaded a universal wheel.
