### ISSUE TITLE
conda-forge maintainers

### ISSUE THREAD

**Issue by alimanfoo** [atdt/monotonic#17]
Hi @atdt, I am developing a Python package ([Zarr](http://zarr.readthedocs.io/en/latest/)) which depends on monotonic via fasteners. I recently added Zarr to [conda-forge](http://conda-forge.github.io) to simplify installation for people using conda, and as part of making that possible I also needed to add monotonic to conda-forge. I've created a [feedstock for the monotonic package](https://github.com/conda-forge/monotonic-feedstock) and would be very happy to add you as a maintainer, which would mean that you could keep the recipe up to date with any new monotonic releases. Just let me know if you'd like me to add you as a maintainer, and/or anyone else. Thanks again.

**Comment by atdt** [comment]
I'm happy to have you maintain the feedstock. Thank you for that.
