### ISSUE TITLE
Support FreeBSD (currently - RuntimeError no suitable implementation)

### ISSUE THREAD

**Issue by temoto** [atdt/monotonic#21]
Relevant code in similar library: https://github.com/gavinbeatty/python-monotonic-time/blob/master/monotonic_time.py.in#L59

Boils down to:
* Linux `clock_gettime(1, &ts)`
* FreeBSD `clock_gettime(4, &ts)`

where 4 is also `#define CLOCK_MONOTONIC	4` in https://github.com/freebsd/freebsd/blob/master/include/time.h

Please, add support for FreeBSD.

**Comment by temoto** [comment]
I'm sorry just read your source and it ought to support FreeBSD, so there is something unusual.
Error reported for `FreeBSD 10.3-RELEASE-p11`.

**Comment by atdt** [comment]
Sorry for the delay. I'll investigate today.

**Comment by atdt** [comment]
@temoto, I am not able to reproduce.

```
$ uname -a
FreeBSD i21 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11 #0: Mon Oct 24 18:49:24 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
$ python2.7
Python 2.7.13 (default, Jan 12 2017, 01:15:13)
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import monotonic
>>> monotonic.monotonic()
608.683200876
>>> monotonic.monotonic()
610.626433146
```

**Comment by temoto** [comment]
Yes, I'm very sorry for posting this without even reading code.

BTW, somehow Github didn't allow me to close the issue before your reply or timeout, funny.
