### ISSUE TITLE
What happened with commit 9b843d4?

### ISSUE THREAD

**Issue by houglum** [atdt/monotonic#25]
When I look at recent commits on the master branch, I see up through 801c740 ("Merge pull request #24 from jeffreydwalter/master").  However, when browsing by tag, I can see the next commit after that, 9b843d4 ("1.4"). 

We keep a mirror of this repo at gsutil-mirrors/monotonic, and when syncing with your repository, I had to `git checkout 1.4`, then push using the specific commit hash to get our mirror to pick up the latest commit; i.e., `git push --tags github-gsutil-mirror master` would not work, but `git push --tags github-gsutil-mirror 9b843d4:master` did.

**Comment by atdt** [comment]
I'm not sure how the repo got to this state, but I fixed it by running:

```shell
$ git reset --hard 9b843d4826
HEAD is now at 9b843d4826 1.4

$ git push origin HEAD
Total 0 (delta 0), reused 0 (delta 0)
To github.com:atdt/monotonic.git
   801c740456..9b843d4826  HEAD -> master
```
